services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    env_file: 
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./data:/var/lib/mysq"
    ports:
      - "3306:3306"

